### PR TITLE
Always close the InputStreams returned from Jar.getResource

### LINKED ISSUE #45: With a gradle multiproject, SS may be illegally altering a zip and crashing on Linux
I have a gradle multproject, [Binnie's mods](https://github.com/ForestryMC/Binnie).
A Linux build server is set up to automatically build the combined mod jar.
The build crashes at "reobf" every time, and the gradle daemon quits with no error message. [Travis log](https://travis-ci.org/ForestryMC/Binnie/jobs/268782436).

This turned out to be caused by a [JDK crash](https://gist.github.com/mezz/acb36bed5953a044be44341b4a5d2603) which I reported and hope to hear back on.

@cpw was able to reproduce the issue on his Linux machine, and believes the JDK crash is caused by some part of the build process reading a zip file while another is editing it. 
This only crashes on Linux because Windows locks the file and Linux does not.

We suspect SpecialSource is involved, if not I still hope to get your thoughts on this.

### PR DESCRIPTION
**Pull request by nallar**
Jar.getResource returns an InputStream which should be closed. It isn't always.

~~Might fix #45, might not. 😖~~ Fixes #45

### CODE REVIEW

**Comment by nallar** [comment]
Force pushed to fix a whitespace error.

**Comment by mezz** [comment]
This, combined with some similar fixes in FG, fixes my issue in #45.

**Comment by mezz** [comment]
@md-5 could you create an SS build with this change and without the Java 9 changes?
It is possible to fix my issue with this change, but it may be hard for me to convince FG to update to using an SS with preliminary Java 9 support.

**Comment by AbrarSyed** [comment]
looking at the commit.. seems all you did was update to ASM6? I dont think that will be a huge breaking change unless the generated bytecode is significantly different...

**Comment by mezz** [comment]
Well it did work fine with the mods I tested, but I wouldn't want to break someone somehow.
If it's fine then that makes things a lot easier.

**Comment by md-5** [comment]
ASM6 is not backwards compatible with ASM5, and in some cases those incompatibilities aren't obvious until runtime (eg the change to RemappingClassAdapter). If ForgeGradle uses ASM outside of via SpecialSource (I'm guessing it does), there is a good chance it will need a change somewhere. The bytecode should be the same however once its actually working.

File: src/main/java/net/md_5/specialsource/Jar.java [hunk 1]
```diff
@@ -75,8 +75,17 @@
      * @return
      */
     public boolean containsClass(String clazz) {
+        if (contains.contains(clazz)) {
+            return true;
+        }
+
         try {
-            return contains.contains(clazz) ? true : getClass(clazz) != null;
+            InputStream current = getClass(clazz);
```
Comment (md-5) [inline src/main/java/net/md_5/specialsource/Jar.java]: If you're modifying this, then you may as well not be using the input stream and check add proper contains methods for classes / resources to eliminate the waste of opening an inputstream and closing it on the next line.

File: src/main/java/net/md_5/specialsource/repo/JarRepo.java [hunk 2]
```diff
@@ -48,7 +48,12 @@ protected ClassNode findClass0(String internalName) {
             InputStream is = jar.getClass(internalName);
 
             if (is != null) {
-                ClassReader reader = new ClassReader(is);
+                ClassReader reader;
+                try {
+                    reader = new ClassReader(is);
+                } finally {
+                    is.close();
```
Comment (md-5) [inline src/main/java/net/md_5/specialsource/repo/JarRepo.java]: Double closing the stream now, .close is called again a few lines below. Really this entire method should just be a call to jar.getNode, the code is duplicated currently.

File: src/main/java/net/md_5/specialsource/SpecialSource.java [hunk 3]
```diff
@@ -299,8 +299,18 @@ private static void visit(Pair<Jar> jars, Pair<JarComparer> visitors, Pair<Strin
...
-        ClassReader clazz1 = new ClassReader(jars.first.getClass(classes.first));
-        ClassReader clazz2 = new ClassReader(jars.second.getClass(classes.second));
+        ClassReader clazz1, clazz2;
+        InputStream first = null;
+        InputStream second = null;
+        try {
+            clazz1 = new ClassReader(first = jars.second.getClass(classes.first));
+            clazz2 = new ClassReader(second = jars.first.getClass(classes.second));
+        } finally {
+            if (first != null)
```
Comment (md-5) [inline src/main/java/net/md_5/specialsource/SpecialSource.java]: Formatting

File: src/main/java/net/md_5/specialsource/JarRemapper.java [hunk 4]
```diff
@@ -209,8 +209,12 @@ public void remapJar(Jar jar, File target) throws IOException {
                         buffer.flush();
                         data = buffer.toByteArray();
                     }
-                    out.putNextEntry(entry);
-                    out.write(data);
+                    try {
```
Comment (md-5) [inline src/main/java/net/md_5/specialsource/JarRemapper.java]: I mean I guess its fine to include this, but it doesn't change functionality at all (see javadoc for .close and .putNextEntry - the entry will *always* be closed with the current code).

File: src/main/java/net/md_5/specialsource/Jar.java (hunk 1 above)
Comment (nallar) [inline src/main/java/net/md_5/specialsource/Jar.java]: This was the minimal change to fix this.

Possibly it would be more correct to add a method getZipEntry which is like getResource but doesn't try to open the entry?

However in that case if trying to open the entry would fail then we could incorrectly return true in containsClass. Not sure if we ever actually would get a non-null result from getEntry but fail to open the stream in practice.

Comment (nallar) [reply src/main/java/net/md_5/specialsource/Jar.java]: 😆 
We nearly simultaneously commented about the same thing.

I'll change it tonight.

File: src/main/java/net/md_5/specialsource/JarRemapper.java (hunk 4 above)
Comment (nallar) [reply src/main/java/net/md_5/specialsource/JarRemapper.java]: `putNextEntry` does `closeEntry` for you, but `close` doesn't. It's quite odd.

This means that the sanity checking [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/zip/ZipOutputStream.java#258) never runs for the last entry if you don't call closeEntry.

File: src/main/java/net/md_5/specialsource/repo/JarRepo.java (hunk 2 above)
Comment (nallar) [reply src/main/java/net/md_5/specialsource/repo/JarRepo.java]: My bad. Will refactor it as suggested.

File: src/main/java/net/md_5/specialsource/SpecialSource.java (hunk 3 above)
Comment (nallar) [reply src/main/java/net/md_5/specialsource/SpecialSource.java]: Missing  `{` `}` or something else?

File: src/main/java/net/md_5/specialsource/JarRemapper.java (hunk 4 above)
Comment (nallar) [reply src/main/java/net/md_5/specialsource/JarRemapper.java]: Scratch that, I'm wrong. Sorry. Will revert this change.

`close()` calls `super.close()` which calls `finish()` which is overridden and calls `closeEntry()`

File: src/main/java/net/md_5/specialsource/Jar.java [hunk 5]
```diff
@@ -75,12 +75,26 @@
      * @return
      */
     public boolean containsClass(String clazz) {
-        try {
-            return contains.contains(clazz) ? true : getClass(clazz) != null;
-        } catch (IOException ex) {
-            // IO error - regardless we do not have access to the class, so we can ignore it and move on
```
Comment (nallar) [inline src/main/java/net/md_5/specialsource/Jar.java]: This code no longer has the same behaviour as before - if we would ever actually get to this point, we will now incorrectly return true.

Shouldn't happen unless the jar file is modified or deleted while we're using it.

File: src/main/java/net/md_5/specialsource/Jar.java [hunk 6]
```diff
@@ -75,12 +75,26 @@
...
+
+    /**
+     * Check if this jar contains the given resource.
+     *
+     * @param name The name of the resource
+     * @return true Whether a resource with the given name exists
+     */
+    public boolean containsResource(String name) {
+        JarFile jarFile = jarForResource.get(name);
+        return jarFile != null && jarFile.getEntry(name) != null;
```
Comment (nallar) [inline src/main/java/net/md_5/specialsource/Jar.java]: The `&& jarFile.getEntry(name) != null` check is probably redundant, it mirrors the check in `getResource`.

Not sure whether or not you want this.

**Comment by nallar** [comment]
Thanks for the review. Hopefully it's okay now.

The change to containsClass in a separate commit as I'm not sure if you actually want it as it changes the behaviour if trying to open the stream would have thrown.
